### ISSUE TITLE
"You found an error" error

### ISSUE THREAD

**Issue by leckert123** [soleon/Percentage#42]
---------------------------
You Found An Error
---------------------------
Battery Percentage Icon version 2.1.3 has run into an error. You can help to fix this by:

1. Press Ctrl+C on this message

2. Report the copied error at https://github.com/soleon/Percentage/issues

System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.

   at Wpf.Ui.Tray.Hicon.FromSource(ImageSource source)

   at Wpf.Ui.Tray.Controls.NotifyIcon.OnIconChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)

   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)

   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)

   at Percentage.App.Extensions.NotifyIconExtensions.SetIcon(NotifyIcon notifyIcon, FrameworkElement textBlock)

   at Percentage.App.Extensions.NotifyIconExtensions.SetBatteryFullIcon(NotifyIcon notifyIcon)

   at Percentage.App.NotifyIconWindow.UpdateBatteryStatus()

   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by leckert123** [comment]
---------------------------
You Found An Error
---------------------------
Battery Percentage Icon version 2.1.3 has run into an error. You can help to fix this by:

1. Press Ctrl+C on this message

2. Report the copied error at https://github.com/soleon/Percentage/issues



System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.

   at Wpf.Ui.Tray.Hicon.FromSource(ImageSource source)

   at Wpf.Ui.Tray.Controls.NotifyIcon.OnIconChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)

   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)

   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)

   at Percentage.App.Extensions.NotifyIconExtensions.SetIcon(NotifyIcon notifyIcon, FrameworkElement textBlock)

   at Percentage.App.Extensions.NotifyIconExtensions.SetBatteryFullIcon(NotifyIcon notifyIcon)

   at Percentage.App.NotifyIconWindow.UpdateBatteryStatus()

   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at Percentage.App.App.Main()
---------------------------
OK   
---------------------------

**Comment by soleon** [comment]
Hi @leckert123 this issue is already fixed in version 2.1.4. Please update the app to the latest version in Microsoft Store to solve this problem.

Closing, duplicated with issue #25.

**Comment by leckert123** [comment]
I have 2.14 installed from the MS store and have the same issue still.
![image](https://github.com/user-attachments/assets/939dd4cf-c4f2-4ac2-a240-e365566a44b2)

**Comment by soleon** [comment]
Hi @leckert123 when the error happens again, can you copy the full error details which should begin with something like “ Battery Percentage Icon version 2.1.4 has run into an error”.

The full detail can help me to determine the root cause of the issue.

Thanks.

**Comment by leckert123** [comment]
My mistake. I was sleep-typing, apparently.:)  I'm no longer getting **this** error, with the pop-up as described. 

I'm still getting the **other issue**, where the app disappears after some time. Typically it's when the machine goes to sleep.
